// Crisis & Professional Support Pathway
// Emergency resources, crisis hotlines, and professional referral guidance

export interface CrisisResource {
  id: string;
  region: "global" | "us" | "uk" | "kr" | "eu";
  type: "emergency" | "hotline" | "textline" | "online" | "directory";
  nameEn: string;
  nameKo: string;
  descEn: string;
  descKo: string;
  phone?: string;
  text?: string;
  website?: string;
  availableEn: string;
  availableKo: string;
}

export const CRISIS_RESOURCES: CrisisResource[] = [
  // === Emergency ===
  {
    id: "emergency-uk",
    region: "uk",
    type: "emergency",
    nameEn: "Emergency Services (UK)",
    nameKo: "응급 서비스 (영국)",
    descEn: "Immediate danger to life — call 999",
    descKo: "생명에 위험이 있을 때 — 999번으로 전화",
    phone: "999",
    availableEn: "24/7",
    availableKo: "24시간",
  },
  {
    id: "emergency-us",
    region: "us",
    type: "emergency",
    nameEn: "Emergency Services (US)",
    nameKo: "응급 서비스 (미국)",
    descEn: "Immediate danger to life — call 911",
    descKo: "생명에 위험이 있을 때 — 911번으로 전화",
    phone: "911",
    availableEn: "24/7",
    availableKo: "24시간",
  },
  {
    id: "emergency-kr",
    region: "kr",
    type: "emergency",
    nameEn: "Emergency Services (Korea)",
    nameKo: "응급 서비스 (한국)",
    descEn: "Immediate danger — call 119",
    descKo: "위급 상황 — 119번으로 전화",
    phone: "119",
    availableEn: "24/7",
    availableKo: "24시간",
  },
  {
    id: "emergency-eu",
    region: "eu",
    type: "emergency",
    nameEn: "Emergency Services (EU)",
    nameKo: "응급 서비스 (유럽)",
    descEn: "Immediate danger — call 112",
    descKo: "위급 상황 — 112번으로 전화",
    phone: "112",
    availableEn: "24/7",
    availableKo: "24시간",
  },

  // === Mental health crises ===
  {
    id: "samhritain",
    region: "uk",
    type: "hotline",
    nameEn: "Samaritans (UK & Ireland)",
    nameKo: "사마리탄스 (영국·아일랜드)",
    descEn: "Free confidential listening, any emotional crisis",
    descKo: "무료 기밀 상담, 감정적 위기",
    phone: "116 123",
    availableEn: "24/7",
    availableKo: "24시간",
  },
  {
    id: "shout-uk",
    region: "uk",
    type: "textline",
    nameEn: "Shout (UK Text Crisis Line)",
    nameKo: "Shout (영국 문자 위기 상담)",
    descEn: "Text-based crisis support",
    descKo: "문자 기반 위기 상담",
    text: "85258",
    availableEn: "24/7",
    availableKo: "24시간",
  },
  {
    id: "ninelife-us",
    region: "us",
    type: "hotline",
    nameEn: "988 Suicide & Crisis Lifeline (US)",
    nameKo: "988 자살예방 위기 상담 (미국)",
    descEn: "Free, confidential support for people in distress",
    descKo: "위기에 처한 분을 위한 무료 기밀 지원",
    phone: "988",
    availableEn: "24/7",
    availableKo: "24시간",
  },
  {
    id: "crisis-text-us",
    region: "us",
    type: "textline",
    nameEn: "Crisis Text Line (US)",
    nameKo: "위기 문자 상담 (미국)",
    descEn: "Free 24/7 crisis support by text",
    descKo: "무료 24시간 문자 위기 상담",
    text: "Text HOME to 741741",
    availableEn: "24/7",
    availableKo: "24시간",
  },
  {
    id: "korea-suicide",
    region: "kr",
    type: "hotline",
    nameEn: "Korea Suicide Prevention Hotline",
    nameKo: "자살예방 상담전화",
    descEn: "Confidential emotional support and crisis intervention",
    descKo: "기밀 감정 지원 및 위기 개입",
    phone: "1393",
    availableEn: "24/7",
    availableKo: "24시간",
  },
  {
    id: "korea-mental",
    region: "kr",
    type: "hotline",
    nameEn: "Korea Mental Health Hotline",
    nameKo: "정신건강 상담전화",
    descEn: "Mental health support and referrals",
    descKo: "정신건강 지원 및 의뢰",
    phone: "1577-0199",
    availableEn: "9am-6pm",
    availableKo: "오전 9시-오후 6시",
  },

  // === Parenting-specific ===
  {
    id: "nspcc",
    region: "uk",
    type: "hotline",
    nameEn: "NSPCC Helpline (UK)",
    nameKo: "NSPCC 헬프라인 (영국)",
    descEn: "Concerned about a child's safety or welfare",
    descKo: "아이의 안전이나 복지가 걱정될 때",
    phone: "0808 800 5000",
    website: "nspcc.org.uk",
    availableEn: "Mon-Fri 8am-10pm, weekends 9am-6pm",
    availableKo: "평일 오전 8시-오후 10시, 주말 오전 9시-오후 6시",
  },
  {
    id: "childline-uk",
    region: "uk",
    type: "hotline",
    nameEn: "Childline (UK)",
    nameKo: "차일드라인 (영국)",
    descEn: "Free, confidential support for children and young people",
    descKo: "아동·청소년을 위한 무료 기밀 지원",
    phone: "0800 1111",
    website: "childline.org.uk",
    availableEn: "24/7",
    availableKo: "24시간",
  },
  {
    id: "childhelp-us",
    region: "us",
    type: "hotline",
    nameEn: "Childhelp National Child Abuse Hotline (US)",
    nameKo: "Childhelp 전국 아동학대 핫라인 (미국)",
    descEn: "Child abuse prevention and intervention",
    descKo: "아동학대 예방 및 개입",
    phone: "1-800-422-4453",
    availableEn: "24/7",
    availableKo: "24시간",
  },
  {
    id: "parent-helpline-us",
    region: "us",
    type: "hotline",
    nameEn: "Parent Stress Line (US)",
    nameKo: "부모 스트레스 상담 (미국)",
    descEn: "Support for overwhelmed parents",
    descKo: "지친 부모를 위한 지원",
    phone: "1-800-632-8188",
    availableEn: "24/7",
    availableKo: "24시간",
  },
  {
    id: "korea-child",
    region: "kr",
    type: "hotline",
    nameEn: "Korea Child Abuse Report",
    nameKo: "아동학대 신고전화",
    descEn: "Report suspected child abuse",
    descKo: "아동학대가 의심될 때 신고",
    phone: "112",
    availableEn: "24/7",
    availableKo: "24시간",
  },

  // === Online directories ===
  {
    id: "psychology-today",
    region: "global",
    type: "directory",
    nameEn: "Psychology Today Therapist Finder",
    nameKo: "심리 치료사 찾기 (Psychology Today)",
    descEn: "Find licensed therapists, filtered by specialty, insurance, and location",
    descKo: "전문 분야, 보험, 지역별로 심리 치료사 검색",
    website: "psychologytoday.com",
    availableEn: "Online directory",
    availableKo: "온라인 디렉토리",
  },
  {
    id: "nhs-talk",
    region: "uk",
    type: "directory",
    nameEn: "NHS Talking Therapies (UK)",
    nameKo: "NHS 심리상담 (영국)",
    descEn: "Free NHS therapy services — self-refer without seeing GP",
    descKo: "무료 NHS 심리 치료 — GP 없이 자가 의뢰 가능",
    website: "nhs.uk/mental-health/talking-therapies-medicine-treatments/talking-therapies-and-counselling/nhs-talking-therapies/",
    availableEn: "Self-referral",
    availableKo: "자가 의뢰",
  },
  {
    id: "korea-counseling",
    region: "kr",
    type: "directory",
    nameEn: "Korea Counseling Psychology Association",
    nameKo: "한국상담심리학회",
    descEn: "Find licensed counseling psychologists in Korea",
    descKo: "한국의 상담 심리 전문가 검색",
    website: "counseling.or.kr",
    availableEn: "Online directory",
    availableKo: "온라인 디렉토리",
  },
  {
    id: "betterhelp",
    region: "global",
    type: "online",
    nameEn: "BetterHelp",
    nameKo: "BetterHelp",
    descEn: "Online therapy platform — licensed therapists via text, video, phone",
    descKo: "온라인 심리 치료 플랫폼 — 문자, 영상, 전화",
    website: "betterhelp.com",
    availableEn: "Online service",
    availableKo: "온라인 서비스",
  },
];

// === Warning signs that warrant professional help ===
export const WARNING_SIGNS = [
  {
    id: "self-harm",
    icon: "⚠️",
    en: "Thoughts of self-harm or harming others",
    ko: "자해나 타인 해치는 생각",
    urgency: "immediate",
  },
  {
    id: "persistent-sadness",
    icon: "😢",
    en: "Persistent sadness or hopelessness lasting >2 weeks",
    ko: "2주 이상 지속되는 슬픔이나 절망감",
    urgency: "soon",
  },
  {
    id: "child-aggression",
    icon: "😠",
    en: "Child showing severe aggression toward self or others",
    ko: "아이가 자신이나 타인에게 심한 공격성",
    urgency: "soon",
  },
  {
    id: "regression",
    icon: "📉",
    en: "Significant developmental regression (loss of skills)",
    ko: "발달 퇴행 (습득한 능력 상실)",
    urgency: "soon",
  },
  {
    id: "extreme-fear",
    icon: "😰",
    en: "Extreme anxiety, panic, or fears affecting daily life",
    ko: "일상에 영향을 미치는 극도의 불안, 공포",
    urgency: "soon",
  },
  {
    id: "parental-overwhelm",
    icon: "🫠",
    en: "Feeling unable to cope or afraid of losing control",
    ko: "감당할 수 없거나 통제를 잃을 것 같은 느낌",
    urgency: "soon",
  },
  {
    id: "sleep-food",
    icon: "😴",
    en: "Child's sleep or eating severely disrupted for >1 week",
    ko: "아이의 수면이나 식사가 1주일 이상 심각하게 불안정",
    urgency: "monitor",
  },
  {
    id: "social-withdrawal",
    icon: "🚪",
    en: "Child completely withdrawing from social interaction",
    ko: "아이가 사회적 교류를 완전히 중단",
    urgency: "monitor",
  },
];

export const URGENCY_META: Record<string, { color: string; labelEn: string; labelKo: string }> = {
  immediate: { color: "#dc2626", labelEn: "Seek immediate help", labelKo: "즉시 도움을 받으세요" },
  soon: { color: "#f59e0b", labelEn: "Consult a professional soon", labelKo: "조속히 전문가 상담" },
  monitor: { color: "#3b82f6", labelEn: "Monitor and discuss with doctor", labelKo: "관찰하고 의사와 상담" },
};
